version: '3.7'

services: 

  db:
    image: postgres
    ports: 
      - 5432:5432
    container_name: postgresql_container
    environment:
      - POSTGRES_USER=andrey
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dbcardapio
    restart: always

  backend:
    build: ./backend
    container_name: cardapio_backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dbcardapio
      - SPRING_DATASOURCE_USERNAME=andrey
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always